Adds support for loading and running custom classes during startup …
jboss-fuse/original-poc-camel-kafka-connector pull request #66
Opened 2019-10-23 09:04 UTC by orpiske

This should allow, for example, configuring beans and increasing the client setup flexiblity for certain components (ie.: AWS SNS and SQS).

The reason I implemented this is because some clients like AWS gives you the flexibility to configure the underlying client according to your needs.

To do so, this PR adds support for 2 new configurations: 
* camel.sink.startup.helper
* camel.source.startup.helper

These are used to point to a class that implements CamelStartupHelper and receives both the map with all the properties setup for the sink/source (so that they can query it for other configurations) as well as the CamelContext which they can use to - for example - bind key/values on the Camel registry.

For the moment, the PR only has a test for this on top of the AWS SQS Source because I don't want to commit myself too much to this design without some feedback first. If this is good enough, then I'll send a separate PR with a test using this feature and the AWS SQS Sink.

2019-10-23 10:46 UTC, valdar commented
Hi @orpiske, this is an interesting idea worth exploring thanks for the effort.

One question though, were you not able to achieve most of it trough new property bind mechanism from camel 3? 

i.e. adding properties like it is done here:  https://github.com/jboss-fuse/camel-kafka-connector/blob/master/examples/CamelJmsSourceConnector.properties#L11-L12

2019-10-23 10:59 UTC, oscerd requested changes
It looks a bit overkilling. It worth a discussion

2019-10-23 11:13 UTC, orpiske commented
@valdar thanks! I haven't thought about that one and now I think it might do what I would like to do. Let me take a look at that and see if that solves the problem. 

@oscerd thanks! Yeah, I was afraid it could be too much for what I was looking forward doing. Although there may be other use cases for this, we may not need it if I can do it the way @valdar is suggesting.

2019-10-23 12:50 UTC, valdar commented
@orpiske there might definitely be more use-cases for additions like this one, I feel that sooner or later we will need to add a "customizer mechanism" of some sort. 

I would like to keep things as simple as possible as long as we can.
If we find a way to cover your use-case, I prefer to wait to introduce such a feature.

2019-10-23 13:01 UTC, orpiske commented
> @orpiske there might definitely be more use-cases for additions like this one, I feel that sooner or later we will need to add a "customizer mechanism" of some sort.
> 
> I would like to keep things as simple as possible as long as we can.
> If we find a way to cover your use-case, I prefer to wait to introduce such a feature.

+1 for simplicity and waiting. 

The one feature I need from all of this - to test both custom clients on AWS SQS as well as to implement AWS SNS testing - is the ability to do binds on the registry. 

Based on a separate discussion with @oscerd, I think that what you proposed would do 90% of what we need ... However, I still need a way to bind the custom client to the registry.

2019-10-24 15:14 UTC, orpiske commented
@valdar your suggestion of using the new property bind mechanism was right on the spot! 

I did a quick test on a modified version of the code I was playing with and I think it will do the trick. 

Although we might still need to do binds in the registry for other reasons, I think we can close this and reassess the implementation in the future.

Thanks!

2019-10-24 15:14 UTC, closed without merging